import type { FertilizerProduct, PhytoProduct, Product, SeedProduct } from './products.types';

/**
 * Catalogue produits réels utilisés en Suisse romande (Échallens).
 * Numéros OFAG vérifiables sur https://www.psm.admin.ch/fr/produkte
 *
 * À remplacer par fetch Odoo `product.product` en Phase 3.
 */

const PHYTO: PhytoProduct[] = [
  {
    id: 'PHY-001',
    name: 'Adexar',
    type: 'phyto',
    category: 'fungicide',
    ofagNumber: 'W-7239',
    activeSubstance: 'Fluxapyroxad + Epoxiconazole',
    manufacturer: 'BASF',
    withholdingDays: 35,
    defaultDoseUnit: 'L/ha',
    defaultDoseValue: 1.5,
    authorizedCrops: ["Blé d'automne", 'Blé de printemps', "Orge d'automne", 'Orge de printemps'],
    active: true,
  },
  {
    id: 'PHY-002',
    name: 'Moddus Evo',
    type: 'phyto',
    category: 'growth-regulator',
    ofagNumber: 'W-6789',
    activeSubstance: 'Trinexapac-éthyl',
    manufacturer: 'Syngenta',
    withholdingDays: 0,
    defaultDoseUnit: 'L/ha',
    defaultDoseValue: 0.4,
    authorizedCrops: ["Blé d'automne", "Orge d'automne", 'Seigle'],
    active: true,
  },
  {
    id: 'PHY-003',
    name: 'Axial One',
    type: 'phyto',
    category: 'herbicide',
    ofagNumber: 'W-7012',
    activeSubstance: 'Pinoxaden + Florasulam',
    manufacturer: 'Syngenta',
    withholdingDays: 0,
    defaultDoseUnit: 'L/ha',
    defaultDoseValue: 1.0,
    authorizedCrops: ["Blé d'automne", "Orge d'automne"],
    active: true,
  },
  {
    id: 'PHY-004',
    name: 'Calaris',
    type: 'phyto',
    category: 'herbicide',
    ofagNumber: 'W-6234',
    activeSubstance: 'Mésotrione + Terbuthylazine',
    manufacturer: 'Syngenta',
    withholdingDays: 0,
    defaultDoseUnit: 'L/ha',
    defaultDoseValue: 1.5,
    authorizedCrops: ['Maïs ensilage', 'Maïs grain'],
    active: true,
  },
  {
    id: 'PHY-005',
    name: 'Karate Zeon',
    type: 'phyto',
    category: 'insecticide',
    ofagNumber: 'W-5891',
    activeSubstance: 'Lambda-cyhalothrine',
    manufacturer: 'Syngenta',
    withholdingDays: 7,
    defaultDoseUnit: 'L/ha',
    defaultDoseValue: 0.075,
    active: true,
  },
  {
    id: 'PHY-006',
    name: 'Aviator Xpro',
    type: 'phyto',
    category: 'fungicide',
    ofagNumber: 'W-7456',
    activeSubstance: 'Bixafen + Protioconazole',
    manufacturer: 'Bayer',
    withholdingDays: 35,
    defaultDoseUnit: 'L/ha',
    defaultDoseValue: 1.0,
    authorizedCrops: ["Blé d'automne", "Orge d'automne", "Colza d'automne"],
    active: true,
  },
  {
    id: 'PHY-007',
    name: 'Roundup PowerMax',
    type: 'phyto',
    category: 'herbicide',
    ofagNumber: 'W-5012',
    activeSubstance: 'Glyphosate',
    manufacturer: 'Bayer',
    withholdingDays: 7,
    defaultDoseUnit: 'L/ha',
    defaultDoseValue: 3.0,
    active: true,
  },
  {
    id: 'PHY-008',
    name: 'Sluxx HP',
    type: 'phyto',
    category: 'molluscicide',
    ofagNumber: 'W-6890',
    activeSubstance: 'Phosphate de fer',
    manufacturer: 'Neudorff',
    withholdingDays: 0,
    defaultDoseUnit: 'kg/ha',
    defaultDoseValue: 7.0,
    active: true,
  },
  {
    id: 'PHY-009',
    name: 'Plenum',
    type: 'phyto',
    category: 'insecticide',
    ofagNumber: 'W-6701',
    activeSubstance: 'Pymétrozine',
    manufacturer: 'Syngenta',
    withholdingDays: 21,
    defaultDoseUnit: 'kg/ha',
    defaultDoseValue: 0.4,
    authorizedCrops: ["Colza d'automne", 'Betterave sucrière'],
    active: true,
  },
  {
    id: 'PHY-010',
    name: 'Boxer',
    type: 'phyto',
    category: 'herbicide',
    ofagNumber: 'W-4889',
    activeSubstance: 'Prosulfocarbe',
    manufacturer: 'Syngenta',
    withholdingDays: 0,
    defaultDoseUnit: 'L/ha',
    defaultDoseValue: 4.0,
    authorizedCrops: ["Blé d'automne", "Orge d'automne", 'Pomme de terre'],
    active: true,
  },
];

const FERTILIZER: FertilizerProduct[] = [
  // Minéraux : nPerUnit = fraction massique (kg N par kg de produit).
  // Ammonitrate 27% N → 0.27 kg N / kg ; 222 kg/ha × 0.27 = 60 kg N/ha.
  {
    id: 'FER-001',
    name: 'Ammonitrate 27%',
    type: 'fertilizer',
    category: 'mineral',
    manufacturer: 'Landor',
    nPerUnit: 0.27,
    pPerUnit: 0,
    kPerUnit: 0,
    defaultDoseUnit: 'kg/ha',
    active: true,
  },
  {
    id: 'FER-002',
    name: 'Urée 46%',
    type: 'fertilizer',
    category: 'mineral',
    manufacturer: 'Landor',
    nPerUnit: 0.46,
    pPerUnit: 0,
    kPerUnit: 0,
    defaultDoseUnit: 'kg/ha',
    active: true,
  },
  {
    id: 'FER-003',
    name: 'NPK 15-15-15',
    type: 'fertilizer',
    category: 'mineral',
    manufacturer: 'Landor',
    nPerUnit: 0.15,
    pPerUnit: 0.15,
    kPerUnit: 0.15,
    defaultDoseUnit: 'kg/ha',
    active: true,
  },
  {
    id: 'FER-004',
    name: 'NPK 20-5-10',
    type: 'fertilizer',
    category: 'mineral',
    manufacturer: 'Landor',
    nPerUnit: 0.2,
    pPerUnit: 0.05,
    kPerUnit: 0.1,
    defaultDoseUnit: 'kg/ha',
    active: true,
  },
  {
    id: 'FER-005',
    name: 'Patentkali (K-Mg)',
    type: 'fertilizer',
    category: 'mineral',
    manufacturer: 'K+S',
    nPerUnit: 0,
    pPerUnit: 0,
    kPerUnit: 0.3,
    mgPerUnit: 0.1,
    sPerUnit: 0.17,
    defaultDoseUnit: 'kg/ha',
    active: true,
  },
  // Organiques : nPerUnit = kg N par m³ ou par tonne.
  // Lisier bovin : 4.5 kg N/m³ ; 30 m³/ha × 4.5 = 135 kg N/ha.
  {
    id: 'FER-006',
    name: 'Lisier bovin',
    type: 'fertilizer',
    category: 'organic',
    nPerUnit: 4.5,
    pPerUnit: 2.0,
    kPerUnit: 5.5,
    defaultDoseUnit: 'm³/ha',
    active: true,
  },
  // Fumier bovin stocké : ~5.5 kg N/t ; 30 t/ha × 5.5 = 165 kg N/ha.
  {
    id: 'FER-007',
    name: 'Fumier bovin (stocké)',
    type: 'fertilizer',
    category: 'organic',
    nPerUnit: 5.5,
    pPerUnit: 3.0,
    kPerUnit: 7.0,
    defaultDoseUnit: 't/ha',
    active: true,
  },
  {
    id: 'FER-008',
    name: 'Chaux carbonatée',
    type: 'fertilizer',
    category: 'amendment',
    manufacturer: 'Calmasil',
    nPerUnit: 0,
    pPerUnit: 0,
    kPerUnit: 0,
    defaultDoseUnit: 't/ha',
    active: true,
  },
];

const SEED: SeedProduct[] = [
  {
    id: 'SEM-001',
    name: 'Arnold (Blé)',
    type: 'seed',
    cropName: "Blé d'automne",
    varietyName: 'Arnold',
    certified: true,
    manufacturer: 'DSP',
    defaultDoseUnit: 'kg/ha',
    defaultDoseValue: 300,
    active: true,
  },
  {
    id: 'SEM-002',
    name: 'Montalbano (Blé)',
    type: 'seed',
    cropName: "Blé d'automne",
    varietyName: 'Montalbano',
    certified: true,
    manufacturer: 'DSP',
    defaultDoseUnit: 'kg/ha',
    defaultDoseValue: 320,
    active: true,
  },
  {
    id: 'SEM-003',
    name: 'LG31.330 (Maïs)',
    type: 'seed',
    cropName: 'Maïs ensilage',
    varietyName: 'LG31.330',
    certified: true,
    manufacturer: 'Limagrain',
    defaultDoseUnit: 'grains/ha',
    defaultDoseValue: 90000,
    active: true,
  },
  {
    id: 'SEM-004',
    name: 'P0937 (Maïs)',
    type: 'seed',
    cropName: 'Maïs ensilage',
    varietyName: 'P0937',
    certified: true,
    manufacturer: 'Pioneer',
    defaultDoseUnit: 'grains/ha',
    defaultDoseValue: 88000,
    active: true,
  },
  {
    id: 'SEM-005',
    name: 'Forino (Orge)',
    type: 'seed',
    cropName: "Orge d'automne",
    varietyName: 'Forino',
    certified: true,
    manufacturer: 'DSP',
    defaultDoseUnit: 'kg/ha',
    defaultDoseValue: 180,
    active: true,
  },
  {
    id: 'SEM-006',
    name: 'Adriana (Colza)',
    type: 'seed',
    cropName: "Colza d'automne",
    varietyName: 'Adriana',
    certified: true,
    manufacturer: 'DSP',
    defaultDoseUnit: 'kg/ha',
    defaultDoseValue: 4,
    active: true,
  },
  {
    id: 'SEM-007',
    name: 'Mélange Standard 330 (Prairie)',
    type: 'seed',
    cropName: 'Prairie temporaire',
    varietyName: 'Mst 330 (Agridéa)',
    certified: true,
    manufacturer: 'UFA Semences',
    defaultDoseUnit: 'kg/ha',
    defaultDoseValue: 35,
    active: true,
  },
];

export const PRODUCTS: ReadonlyArray<Product> = [...PHYTO, ...FERTILIZER, ...SEED];
